--- 
clone: 
  depth: 1
kind: pipeline
name: Umi
steps: 
  - 
    commands: 
      - "git clone https://github.com/Official-Ayrton990/android_kernel_xiaomi_sm8250.git -b QK-eleven kernel"
      - "curl https://del.dog/raw/kernel_Quantic.sh | bash"
    environment: 
      TG_TOKEN: 
        from_secret: BOT_TOKEN
      image: fadlyas/kernel_dockerfile:latest
      name: Compile
