--- 
clone: 
  depth: 1
kind: pipeline
name: Umi
steps: 
  - 
    commands: 
      - bash build.sh
    environment: 
      TG_TOKEN: 
        from_secret: BOT_TOKEN
      image: fadlyas/kernel_dockerfile:latest
      name: Compile