clone: 
  depth: 1
kind: pipeline
name: Umi
steps: 
  - 
    commands: 
      - "curl https://del.dog/raw/kernel_Quantic.sh | bash"
    environment: 
      TG_TOKEN: 
        from_secret: BOT_TOKEN
      image: fadlyas/kernel_dockerfile:latest
      name: Compile
